### ISSUE TITLE
ImportError: liboptix_prime.so.6.5.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by qsimeng** [lvjiahui/DRT#1]
My Environment: ubuntu 18.04; pytorch 1.3.1

Traceback (most recent call last):
  File "optim.py", line 6, in <module>
    import DiffRender as Render
  File "/home/Code/DRT/DiffRender.py", line 7, in <module>
    extra_include_paths=[optix_include], extra_ldflags=["-L "+optix_ld, "-loptix_prime"])
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1052, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: liboptix_prime.so.6.5.0: cannot open shared object file: No such file or directory

**Comment by lvjiahui** [comment]
Hi qsimeng,
This may be because you didn't set the absolute Optix path in `config.py`.

**Comment by wuweiyexiaomian** [comment]
Add the directory containing the file `/NVIDIA-OptiX-SDK-6.5.0-linux64/lib64/liboptix_prime.so.6.5.0` to the system environment variable (such as LD_LIBRARY_PATH).

**Comment by wuweiyexiaomian** [comment]
If the library file is not present in the default library search path, you can try creating a symbolic link pointing to the actual library file so that the system can locate it. Use the following command: 

``
ln -s /actual/path/to/liboptix_prime.so.6.5.0 /usr/lib/liboptix_prime.so.6.5.0
``
