### ISSUE TITLE
illegal memory access

### ISSUE THREAD

**Issue by wang07380731** [lvjiahui/DRT#9]
**when i run "python optim.py"，i encountered the following error:**
Traceback (most recent call last):
  File "optim.py", line 224, in <module>
    scene = optimize(HyperParams)
  File "optim.py", line 175, in optimize
    scene = Render.Scene(f"{config.data_path}{name}_vh.ply")
  File "/DRT-master/DiffRender.py", line 301, in __init__
    self.update_mesh(mesh_path)
  File "/DRT-master/DiffRender.py", line 313, in update_mesh
    self.optix_mesh.update_mesh(opt_F, opt_v)
RuntimeError: Function "RTPresult _rtpModelUpdate(RTPmodel, unsigned int)" caught exception: Encountered a CUDA error: cudaEventRecord( m_eventEnd, stream ) returned (700): an illegal memory access was encountered

**The environment I configured should be correct. How can I solve this problem? Is it related to the cuda version**

**Comment by wuweiyexiaomian** [comment]
Could you solve it? How did you solve it?

**Comment by wuweiyexiaomian** [comment]
I saw a comment that said this:
"Redner uses Optix 6.5 which will never be compatible with RTX30xx.
https://forums.developer.nvidia.com/t/optix-6-5-prime-samples-fail-with-rtx-3080/177078"

**Comment by wang07380731** [comment]
> I saw a comment that said this: "Redner uses Optix 6.5 which will never be compatible with RTX30xx. https://forums.developer.nvidia.com/t/optix-6-5-prime-samples-fail-with-rtx-3080/177078"

yes, i think the problem is the version of  optix of this project  is too old, so i gave up this project.
